### ISSUE TITLE
Alternative behaviour to configuring non-sync OU within Active Directory

### ISSUE THREAD

**Issue by ChrisAtMAF** [timmcmic/DLConversion#22]
Hi Tim,

Love the script - it's really helpful for performing these migrations.

Just a quick suggestion - at present to use the script, it's necessary to set up a 'non-sync' OU which is ignored by Azure AD Connect so that groups can be 'removed' from AAD while remaining within AD.

Have you considered setting the 'adminDescription' field within Active Directory to something that starts with 'Group_' instead? This will result in the group disappearing from AAD during next sync - it's part of the default AAD Connect sync rules https://blogs.perficient.com/2016/04/11/office-365-the-previously-undocumented-aad-connect-filter/
https://blog.kloud.com.au/2016/07/14/the-new-azure-ad-connect-built-in-user-filter-admindescription/

Makes it easier to use the script without reconfiguring.

Keep up the great work!

**Comment by timmcmic** [comment]
Chris:

That's an awesome suggestion.  The reason I went with the OU is from long term troubleshooting.  We often get escalations on rules based filtering.  Also - with the admin description it doesn't prevent the object import into the metaverse it just filters that azure side of it.  So the objects still contribute to the metaverse which makes support even more confusing...

I use the no-sync OU method to try to keep it obvious...

Tim

**Comment by ChrisAtMAF** [comment]
Tim,

Understood - thanks for getting back to me, and thanks again for the script :)

Kind regards,
Chris
