### ISSUE TITLE
Apostrophes

### ISSUE THREAD

**Issue by omzig10** [timmcmic/DLConversion#8]
Tim,

Edge case, but the following code was required to parse folks with apostrophes in their address/UPN. I like the script.

This is around line 2924, some of your code for reference:

if ( $UserorRecipient -eq "Recipient")
			{
				**$fixedprimarySMTPAddressOrUPN = "$($primarySMTPAddressOrUPN.Replace("'","''"))"**

				$functionCommand = "get-o365recipient -filter {primarySMTPAddress -eq '$fixedprimarySMTPAddressOrUPN'}"
				
				$functionTest = Invoke-Expression $functionCommand

**Comment by timmcmic** [comment]
I'll test this after I finish up some new code i'm publishing.  Thanks for the feedback.

**Comment by timmcmic** [comment]
Fixed version 1.8
