### ISSUE TITLE
ignoreInvalidDLMember = TRUE

### ISSUE THREAD

**Issue by jmaiher** [timmcmic/DLConversion#9]
Script looks promising - but a minor issue.
In my testing - I'm attempting to run it and using the following cmd line: 

.\DLConversion.ps1 -dlToConvert All_US -ignoreInvalidDLMember:$True -ignoreInvalidManagedByMember:$FALSE

I continue to encounter the script existing with: 
ERROR: System.Management.Automation.RuntimeException: User or recipient not found in office 365 - all recipients and users must be in Office 365

Am I misunderstanding the ignoreInvalidDLMember parameter? 

If a user has no mailbox or isn't in O365 - shouldn't the script make note, skip & move on? 
I continue to have to remove the users from the DL in question 1 by 1 to proceed further.

**Comment by timmcmic** [comment]
Thank you for posting.  IGNORE does not allow you to migrate a group where a VALID object that should be in office 365 exists in the group but not in the cloud.

IGNORE only ignores ad objects that would not be there - for example non-mail enabled contacts.

**Comment by jmaiher** [comment]
Are you at Ignite by chance?

On Sep 17, 2019, at 10:54 AM, timmcmic <notifications@github.com> wrote:

﻿

Thank you for posting. IGNORE does not allow you to migrate a group where a VALID object that should be in office 365 exists in the group but not in the cloud.

IGNORE only ignores ad objects that would not be there - for example non-mail enabled contacts.

**Comment by timmcmic** [comment]
Unfortunately not this trip.

Tim

Timothy J. McMichael
Senior Support Escalation Engineer
TIMMCMIC@microsoft.com<mailto:TIMMCMIC@microsoft.com>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Backup:  Chad Coker (chcoke@microsoft.com<mailto:chcoke@microsoft.com>)
Backup Hours:  Wednesday – Saturday 08:00 – 16:00 eastern time zone.

Manager:  John Sims (josims@microsoft.com<mailto:josims@microsoft.com>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900
